services:
  - type: web
    name: cv-screening-backend
    env: docker
    rootDir: .
    dockerfilePath: Dockerfile
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT cv_screening_project.wsgi:application
