services:
  - type: web
    name: cv-screening-backend
    env: docker
    rootDir: .
    dockerfilePath: Dockerfile
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn cv_screening_project.wsgi:application --timeout 120 --workers 1 --threads 2
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cv-screening-backend.onrender.com,cv-screeneing-9.onrender.com,.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://cv-screening-ten.vercel.app,https://cv-screening-backend.onrender.com,https://cv-screeneing-9.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://cv-screening-ten.vercel.app,https://cv-screening-backend.onrender.com,https://cv-screeneing-9.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: DATABASE_URL
        value: postgresql://user:password@host:port/dbname
      - key: JWT_SECRET_KEY
        generateValue: true
