# Generated by Django 4.2.8 on 2026-02-19 05:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('hr', 'HR Personnel'), ('applicant', 'Applicant')], max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active_user', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name_plural': 'Custom Users',
                'db_table': 'custom_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv_file', models.FileField(upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary CV for screening')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_uploads', to='cv_screening_app.applicant')),
            ],
            options={
                'verbose_name_plural': 'CV Uploads',
                'db_table': 'cv_uploads',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='HRPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('company_location', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to='cv_screening_app.customuser')),
            ],
            options={
                'verbose_name_plural': 'HR Personnel',
                'db_table': 'hr_personnel',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('application_score', models.FloatField(blank=True, help_text='Automated ranking score', null=True)),
                ('application_rank', models.IntegerField(blank=True, help_text='Rank among applicants for this job', null=True)),
                ('skills_score', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('education_score', models.FloatField(blank=True, null=True)),
                ('hr_notes', models.TextField(blank=True, null=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='cv_screening_app.applicant')),
                ('cv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cv_screening_app.cvupload')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
                'db_table': 'job_applications',
                'ordering': ['-application_score', '-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated list of required skills')),
                ('preferred_skills', models.TextField(blank=True, help_text='Comma-separated list of preferred skills', null=True)),
                ('required_education', models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], max_length=50)),
                ('required_experience', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level')], max_length=20)),
                ('years_of_experience_min', models.IntegerField(default=0)),
                ('years_of_experience_max', models.IntegerField(default=10)),
                ('location', models.CharField(max_length=255)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('job_type', models.CharField(default='Full-time', help_text='Full-time, Part-time, Contract, etc.', max_length=50)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='cv_screening_app.hrpersonnel')),
            ],
            options={
                'verbose_name_plural': 'Job Postings',
                'db_table': 'job_postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills_weight', models.FloatField(default=40, help_text='Weight for skills matching (0-100)')),
                ('experience_weight', models.FloatField(default=30, help_text='Weight for experience (0-100)')),
                ('education_weight', models.FloatField(default=30, help_text='Weight for education (0-100)')),
                ('min_experience_years', models.IntegerField(default=0)),
                ('min_skills_match', models.FloatField(default=30, help_text='Minimum % of skills to match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_criteria', to='cv_screening_app.jobposting')),
            ],
            options={
                'verbose_name_plural': 'Screening Criteria',
                'db_table': 'screening_criteria',
            },
        ),
        migrations.CreateModel(
            name='ParsedCVData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(default=list, help_text='List of extracted skills')),
                ('education', models.JSONField(default=list, help_text='List of education records')),
                ('highest_education', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.JSONField(default=list, help_text='List of work experience records')),
                ('total_years_experience', models.FloatField(blank=True, null=True)),
                ('certifications', models.JSONField(default=list, help_text='List of certifications')),
                ('languages', models.JSONField(default=list, help_text='List of languages')),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('extraction_confidence', models.FloatField(blank=True, help_text='Confidence score of extraction (0-100)', null=True)),
                ('cv_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data_record', to='cv_screening_app.cvupload')),
            ],
            options={
                'verbose_name_plural': 'Parsed CV Data',
                'db_table': 'parsed_cv_data',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('application_status', 'Application Status Update'), ('job_new', 'New Job Posted'), ('interview', 'Interview Scheduled'), ('hiring_decision', 'Hiring Decision'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_screening_app.jobapplication')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_screening_app.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cv_screening_app.customuser')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cv_screening_app.jobposting'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('download', 'Download'), ('decision', 'Decision Made')], max_length=20)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_screening_app.customuser')),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to='cv_screening_app.customuser'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('applicant', 'job')},
        ),
    ]
