from django.core.management.base import BaseCommand
from django.db import transaction

from cv_screening_app.cv_parser import CVParser
from cv_screening_app.models import CVUpload, ParsedCVData


class Command(BaseCommand):
    help = "Re-parse uploaded CV files to refresh extracted NLP fields."

    def add_arguments(self, parser):
        parser.add_argument(
            "--include-builder",
            action="store_true",
            help="Also reparse CVs generated by the template/builder.",
        )
        parser.add_argument(
            "--limit",
            type=int,
            default=0,
            help="Optional limit for number of CVs to reparse.",
        )

    def handle(self, *args, **options):
        include_builder = bool(options.get("include_builder"))
        limit = int(options.get("limit") or 0)

        queryset = CVUpload.objects.all().order_by("upload_date")
        if not include_builder:
            queryset = queryset.exclude(parsed_data__template_source="builder")
        if limit > 0:
            queryset = queryset[:limit]

        total = queryset.count()
        if total == 0:
            self.stdout.write(self.style.WARNING("No CVs found to reparse."))
            return

        parser = CVParser()
        updated = 0
        skipped = 0

        for cv in queryset:
            if not cv.cv_file:
                skipped += 1
                continue
            try:
                parsed = parser.parse_cv(cv.cv_file.path)
            except Exception:
                parsed = None

            if not parsed:
                skipped += 1
                continue

            with transaction.atomic():
                cv.extracted_text = parsed.get("extracted_text", "") or ""
                cv.save(update_fields=["extracted_text"])
                ParsedCVData.objects.update_or_create(
                    cv_upload=cv,
                    defaults={
                        "full_name": parsed.get("full_name"),
                        "email": parsed.get("email"),
                        "phone_number": parsed.get("phone_number"),
                        "location": parsed.get("location"),
                        "summary": parsed.get("summary"),
                        "skills": parsed.get("skills", []),
                        "education": parsed.get("education", []),
                        "highest_education": parsed.get("highest_education") or "high_school",
                        "work_experience": parsed.get("work_experience", []),
                        "total_years_experience": parsed.get("total_years_experience") or 0,
                        "certifications": parsed.get("certifications", []),
                        "languages": parsed.get("languages", []),
                        "extraction_confidence": 100,
                    },
                )
            updated += 1

        self.stdout.write(self.style.SUCCESS(
            f"Reparse complete. Updated {updated} CV(s), skipped {skipped}."
        ))
